name: Generate pacman animation

on:
  schedule: # execute every 24 hours
    - cron: "0 0 */6 * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pacman-contribution-graph
        run: npm install -g pacman-contribution-graph

      - name: Generate pacman SVG
        run: |
          mkdir -p dist
          pacman-contribution-graph --platform github --username ${{ github.repository_owner }} --gameTheme github --output dist/pacman-contribution-graph.svg

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update pacman contribution graph" || exit 0
          git push
